services:
  node-app:
    image: farouq666/testingdockerwithdeployapptoaws
    env_file:
      - ./.env 
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-dp:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      GLIBC_TUNABLES: glibc.pthread.rseq=1

  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-dp: