services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production

    volumes:
      - ./src:/app/src:ro

    environment:
      - NODE_ENV=development

    command: npm run start-dev